name: Build

on:
  push:
  schedule:
    - cron: "5 1 * * *" # Run nightly
  workflow_dispatch:

jobs:
  build:
    name: Building the player
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: 20.5.0

      - name: make clean
        run: make clean

      - name: make init
        run: make init

      - name: make build
        run: make build